// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFKkYvKpOPsYcH_iBB3nVCdeWHsbZdigk',
    appId: '1:882697483403:web:52d9e8c3ba7a81315b108e',
    messagingSenderId: '882697483403',
    projectId: 'drive2go-242c2',
    authDomain: 'drive2go-242c2.firebaseapp.com',
    storageBucket: 'drive2go-242c2.appspot.com',
    measurementId: 'G-3F7EDH73MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkiSvIXKb8-Tf8xIk6QO1zEE-Cl2ZuqrI',
    appId: '1:882697483403:android:6cba323ed25c55b55b108e',
    messagingSenderId: '882697483403',
    projectId: 'drive2go-242c2',
    storageBucket: 'drive2go-242c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWPabYUIU4R9ggyDRC3sxPDt3m4lK3wUY',
    appId: '1:882697483403:ios:6eade47ec7030ac85b108e',
    messagingSenderId: '882697483403',
    projectId: 'drive2go-242c2',
    storageBucket: 'drive2go-242c2.appspot.com',
    iosBundleId: 'com.example.drive2goo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWPabYUIU4R9ggyDRC3sxPDt3m4lK3wUY',
    appId: '1:882697483403:ios:6eade47ec7030ac85b108e',
    messagingSenderId: '882697483403',
    projectId: 'drive2go-242c2',
    storageBucket: 'drive2go-242c2.appspot.com',
    iosBundleId: 'com.example.drive2goo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFKkYvKpOPsYcH_iBB3nVCdeWHsbZdigk',
    appId: '1:882697483403:web:5c485f644c7268145b108e',
    messagingSenderId: '882697483403',
    projectId: 'drive2go-242c2',
    authDomain: 'drive2go-242c2.firebaseapp.com',
    storageBucket: 'drive2go-242c2.appspot.com',
    measurementId: 'G-HPDNLNXT7T',
  );
}
